version: '3.6'
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf/:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=spiffo47
      - DOCKER_INFLUXDB_INIT_ORG=cyber23
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket01
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      - GF_SERVER_DOMAIN=portainer.wh5
      - GF_SERVER_HTTP_PORT=5000
    links:
      - influxdb
    ports:
      - '5000:5000'
    volumes:
      - grafana_data:/var/lib/grafana
      
volumes:
  grafana_data: {}
  influxdb_data: {}
